services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: hoangtu01/backend:latest
    container_name: backend
    environment:
      NODE_ENV: production
      DB_CONNECTION_STRING: mongodb://user:pass@host:27017/dbname
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: hoangtu01/frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
