version: "3.9"

services:
  backend:
    image: hoangngoctu/backend:latest
    container_name: backend
    ports:
      - "3000:3000"
    restart: always

  frontend:
    image: hoangngoctu/frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    restart: always
